trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs: 
  - job: first_job
    steps: 
    - script: |
        echo building first job.
        echo printing enviroment variable sercret.
    - bash: echo $(UnderstandingStagesVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo Source branch $(Build.SourceBranchName)
    - bash: echo artifcat staging dir $(Build.ArtifactStagingDirectory)
    # - bash: java -version
    - bash: node --version
    - bash: python3 --version
    - bash: ls -R $(Build.ArtifactStagingDirecotry)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirecotry)'
    - bash: ls -R $(Build.ArtifactStagingDirecotry)

  - job: second_job
    dependsOn: first_job
    steps: 
    - script: |
        echo running second job.
        echo finished running second job.


# - stage: DevDeploy
#   variables:
#     enviromentName: DEV
#   dependsOn: Build
#   jobs: 
#   - job: dev_deploy_firstjob
#     steps:
#     - bash: echo deploying to dev command 1.
#   - job: dev_deploy_secondjob
#     dependsOn: dev_deploy_firstjob
#     steps: 
#     - bash: echo deploying to $(enviromentName) command 2.

# - stage: QADeploy
#   dependsOn: DevDeploy
#   jobs: 
#   - job: QA_deploy_firstjob
#     steps: 
#     - bash: echo QA deploy command 1
#   - job: QA_deploy_secondjob
#     dependsOn: QA_deploy_firstjob
#     steps: 
#     - bash: echo QA deploy commad 2

# - stage: ProdDeploy
  # dependsOn: QADeploy
  # jobs: 
  # - job: Prod_deploy_job
  #   steps:
  #   - bash: echo Prod deploy command 1

