trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs: 
  - job: build_job
    steps: 
    - script: |
        echo building first job.
        echo printing enviroment variable sercret.
    - bash: echo $(UnderstandingStagesVariable)

- stage: DevDeploy
  variables:
    enviromentName: DEV
  dependsOn: Build
  jobs: 
  - job: dev_deploy_firstjob
    steps:
    - bash: echo deploying to dev command 1.
  - job: dev_deploy_secondjob
    dependsOn: dev_deploy_firstjob
    steps: 
    - bash: echo deploying to $(enviromentName) command 2.

- stage: QADeploy
  dependsOn: DevDeploy
  jobs: 
  - job: QA_deploy_firstjob
    steps: 
    - bash: echo QA deploy command 1
  - job: QA_deploy_secondjob
    dependsOn: QA_deploy_firstjob
    steps: 
    - bash: echo QA deploy commad 2

- stage: ProdDeploy
  dependsOn: QADeploy
  jobs: 
  - job: Prod_deploy_job
    steps:
    - bash: echo Prod deploy command 1

