trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs: 
  - job: build-job
    steps: 
      - bash: echo building first job.

- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: dev-deploy-job1
    steps:
    - bash: echo deploying to dev command 1.
  - job: dev-deploy-job2
    dependsOn: dev-deploy-job1
    steps: 
    - bash: echod deploying to dev command 2.

- stage: QADeploy
  dependsOn: DevDeploy
  jobs: 
  - job: QA-deploy-job1
    steps: 
    - bash: echo QA deploy command 1
  - job: QA-deploy-job2
    dependsOn: QA-deploy-job1
    steps: 
    - bash: echo QA deploy commad 2

- stage: ProdDeploy
  dependsOn: QADeploy
  jobs: 
  - job: Prod-deploy-job1
    steps:
    - bash: echo Prod deploy command 1

