trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  name: Default
  # vmImage: ubuntu-latest
  
stages:
# stage 1: Build / publish docker image
- stage:
  displayName: Build image
  jobs:
    - job: Build
      displayName: Build
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker hub connection.'
          repository: 'foloo12/currency-exchange-devops'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirecotry)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifets'
          publishLocation: 'Container'

# stage 2: Deploying
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy job
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifets'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory )'
    
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'foloo12/currency-exchange-devops:$(tag)'