apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: currencyexchange
   name: currencyexchange
   namespace: default
spec:
   replicas: 1
   minReadySeconds: 45
   selector:
      matchLabels:
         app: currencyexchange
   strategy:
      rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
      type: RollingUpdate
   template:
      metadata:
         labels:
            app: currencyexchange
      spec:
         containers:
            - image: in28min/currency-exchange:0.0.1-RELEASE
              imagePullPolicy: IfNotPresent
              name: currency-exchange
              ports:
                 - name: livenessport
                   containerPort: 8000
              resources:
                 requests:
                    cpu: 100m
                    memory: 512Mi
                    limits:
                       cpu: 500m
                       memory: 1024Mi
                 readinessProbe:
                    httpGet:
                       path: /
                       port: livenessport
                    failureThreshold: 5
                    periodSeconds: 10
                    initialDelaySeconds: 60
                 livenessProbe:
                    httpGet:
                       path: /
                       port: livenessport
                    failureThreshold: 5
                    periodSeconds: 10
                    initialDelaySeconds: 60
              restartPolicy: Always
              terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
   labels:
      app: currencyexchange
   name: currencyexchange
   namespace: default
spec:
   ports:
      - port: 8000
        protocol: TCP
        targetPort: 8000
   selector:
      app: currencyexchange
   sessionAffinity: None
   type: LoadBalancer
